//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayDev.MediaScribe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JayDev.MediaScribe.KeyNames", typeof(KeyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AbntC1 {
            get {
                return ResourceManager.GetString("AbntC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AbntC2 {
            get {
                return ResourceManager.GetString("AbntC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Attn {
            get {
                return ResourceManager.GetString("Attn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowserBack {
            get {
                return ResourceManager.GetString("BrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowserFavorites {
            get {
                return ResourceManager.GetString("BrowserFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowserForward {
            get {
                return ResourceManager.GetString("BrowserForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowserHome {
            get {
                return ResourceManager.GetString("BrowserHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowserRefresh {
            get {
                return ResourceManager.GetString("BrowserRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowserSearch {
            get {
                return ResourceManager.GetString("BrowserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BrowserStop {
            get {
                return ResourceManager.GetString("BrowserStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CapsLock {
            get {
                return ResourceManager.GetString("CapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CrSel {
            get {
                return ResourceManager.GetString("CrSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string D0 {
            get {
                return ResourceManager.GetString("D0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string D5 {
            get {
                return ResourceManager.GetString("D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string D6 {
            get {
                return ResourceManager.GetString("D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string D8 {
            get {
                return ResourceManager.GetString("D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string D9 {
            get {
                return ResourceManager.GetString("D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeAlphanumeric {
            get {
                return ResourceManager.GetString("DbeAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeCodeInput {
            get {
                return ResourceManager.GetString("DbeCodeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeDbcsChar {
            get {
                return ResourceManager.GetString("DbeDbcsChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeDetermineString {
            get {
                return ResourceManager.GetString("DbeDetermineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeEnterDialogConversionMode {
            get {
                return ResourceManager.GetString("DbeEnterDialogConversionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeEnterImeConfigureMode {
            get {
                return ResourceManager.GetString("DbeEnterImeConfigureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeEnterWordRegisterMode {
            get {
                return ResourceManager.GetString("DbeEnterWordRegisterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeFlushString {
            get {
                return ResourceManager.GetString("DbeFlushString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeHiragana {
            get {
                return ResourceManager.GetString("DbeHiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeKatakana {
            get {
                return ResourceManager.GetString("DbeKatakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeNoCodeInput {
            get {
                return ResourceManager.GetString("DbeNoCodeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeNoRoman {
            get {
                return ResourceManager.GetString("DbeNoRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeRoman {
            get {
                return ResourceManager.GetString("DbeRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbeSbcsChar {
            get {
                return ResourceManager.GetString("DbeSbcsChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DeadCharProcessed {
            get {
                return ResourceManager.GetString("DeadCharProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EraseEof {
            get {
                return ResourceManager.GetString("EraseEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExSel {
            get {
                return ResourceManager.GetString("ExSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F10 {
            get {
                return ResourceManager.GetString("F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F11 {
            get {
                return ResourceManager.GetString("F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F12 {
            get {
                return ResourceManager.GetString("F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F13 {
            get {
                return ResourceManager.GetString("F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F14 {
            get {
                return ResourceManager.GetString("F14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F15 {
            get {
                return ResourceManager.GetString("F15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F16 {
            get {
                return ResourceManager.GetString("F16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F17 {
            get {
                return ResourceManager.GetString("F17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F18 {
            get {
                return ResourceManager.GetString("F18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F19 {
            get {
                return ResourceManager.GetString("F19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F20 {
            get {
                return ResourceManager.GetString("F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F21 {
            get {
                return ResourceManager.GetString("F21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F22 {
            get {
                return ResourceManager.GetString("F22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F23 {
            get {
                return ResourceManager.GetString("F23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F24 {
            get {
                return ResourceManager.GetString("F24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F8 {
            get {
                return ResourceManager.GetString("F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string F9 {
            get {
                return ResourceManager.GetString("F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinalMode {
            get {
                return ResourceManager.GetString("FinalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HangulMode {
            get {
                return ResourceManager.GetString("HangulMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HanjaMode {
            get {
                return ResourceManager.GetString("HanjaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImeAccept {
            get {
                return ResourceManager.GetString("ImeAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImeConvert {
            get {
                return ResourceManager.GetString("ImeConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImeModeChange {
            get {
                return ResourceManager.GetString("ImeModeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImeNonConvert {
            get {
                return ResourceManager.GetString("ImeNonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImeProcessed {
            get {
                return ResourceManager.GetString("ImeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JunjaMode {
            get {
                return ResourceManager.GetString("JunjaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KanaMode {
            get {
                return ResourceManager.GetString("KanaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KanjiMode {
            get {
                return ResourceManager.GetString("KanjiMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LaunchApplication1 {
            get {
                return ResourceManager.GetString("LaunchApplication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LaunchApplication2 {
            get {
                return ResourceManager.GetString("LaunchApplication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LaunchMail {
            get {
                return ResourceManager.GetString("LaunchMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LeftAlt {
            get {
                return ResourceManager.GetString("LeftAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LeftCtrl {
            get {
                return ResourceManager.GetString("LeftCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LeftShift {
            get {
                return ResourceManager.GetString("LeftShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LineFeed {
            get {
                return ResourceManager.GetString("LineFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LWin {
            get {
                return ResourceManager.GetString("LWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MediaNextTrack {
            get {
                return ResourceManager.GetString("MediaNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MediaPlayPause {
            get {
                return ResourceManager.GetString("MediaPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MediaPreviousTrack {
            get {
                return ResourceManager.GetString("MediaPreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MediaStop {
            get {
                return ResourceManager.GetString("MediaStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumLock {
            get {
                return ResourceManager.GetString("NumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad0 {
            get {
                return ResourceManager.GetString("NumPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad1 {
            get {
                return ResourceManager.GetString("NumPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad2 {
            get {
                return ResourceManager.GetString("NumPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad3 {
            get {
                return ResourceManager.GetString("NumPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad4 {
            get {
                return ResourceManager.GetString("NumPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad5 {
            get {
                return ResourceManager.GetString("NumPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad6 {
            get {
                return ResourceManager.GetString("NumPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad7 {
            get {
                return ResourceManager.GetString("NumPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad8 {
            get {
                return ResourceManager.GetString("NumPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumPad9 {
            get {
                return ResourceManager.GetString("NumPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string Oem1 {
            get {
                return ResourceManager.GetString("Oem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Oem102 {
            get {
                return ResourceManager.GetString("Oem102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Oem2 {
            get {
                return ResourceManager.GetString("Oem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ` (back tick).
        /// </summary>
        internal static string Oem3 {
            get {
                return ResourceManager.GetString("Oem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Oem4 {
            get {
                return ResourceManager.GetString("Oem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ (backslash).
        /// </summary>
        internal static string Oem5 {
            get {
                return ResourceManager.GetString("Oem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string Oem6 {
            get {
                return ResourceManager.GetString("Oem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Oem7 {
            get {
                return ResourceManager.GetString("Oem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Oem8 {
            get {
                return ResourceManager.GetString("Oem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemAttn {
            get {
                return ResourceManager.GetString("OemAttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemAuto {
            get {
                return ResourceManager.GetString("OemAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ (backslash).
        /// </summary>
        internal static string OemBackslash {
            get {
                return ResourceManager.GetString("OemBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemBackTab {
            get {
                return ResourceManager.GetString("OemBackTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemClear {
            get {
                return ResourceManager.GetString("OemClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string OemCloseBrackets {
            get {
                return ResourceManager.GetString("OemCloseBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , (comma).
        /// </summary>
        internal static string OemComma {
            get {
                return ResourceManager.GetString("OemComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemCopy {
            get {
                return ResourceManager.GetString("OemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemEnlw {
            get {
                return ResourceManager.GetString("OemEnlw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemFinish {
            get {
                return ResourceManager.GetString("OemFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - (minus).
        /// </summary>
        internal static string OemMinus {
            get {
                return ResourceManager.GetString("OemMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string OemOpenBrackets {
            get {
                return ResourceManager.GetString("OemOpenBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . (period).
        /// </summary>
        internal static string OemPeriod {
            get {
                return ResourceManager.GetString("OemPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemPipe {
            get {
                return ResourceManager.GetString("OemPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + (plus).
        /// </summary>
        internal static string OemPlus {
            get {
                return ResourceManager.GetString("OemPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / (slash).
        /// </summary>
        internal static string OemQuestion {
            get {
                return ResourceManager.GetString("OemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; (quote).
        /// </summary>
        internal static string OemQuotes {
            get {
                return ResourceManager.GetString("OemQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemSemicolon {
            get {
                return ResourceManager.GetString("OemSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OemTilde {
            get {
                return ResourceManager.GetString("OemTilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa1 {
            get {
                return ResourceManager.GetString("Pa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PageDown {
            get {
                return ResourceManager.GetString("PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PageUp {
            get {
                return ResourceManager.GetString("PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Prior {
            get {
                return ResourceManager.GetString("Prior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Q {
            get {
                return ResourceManager.GetString("Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RightAlt {
            get {
                return ResourceManager.GetString("RightAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RightCtrl {
            get {
                return ResourceManager.GetString("RightCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RightShift {
            get {
                return ResourceManager.GetString("RightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RWin {
            get {
                return ResourceManager.GetString("RWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Scroll {
            get {
                return ResourceManager.GetString("Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SelectMedia {
            get {
                return ResourceManager.GetString("SelectMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VolumeDown {
            get {
                return ResourceManager.GetString("VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VolumeMute {
            get {
                return ResourceManager.GetString("VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VolumeUp {
            get {
                return ResourceManager.GetString("VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
